defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "jeaye"
      layout: "default"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "jeaye"
      layout: "default"

permalink: pretty
url: "http://jeaye.com"
blog_url: "http://blog.jeaye.com"

highlighter: rouge
exclude: [.bundle, vendor, lib]
includes_dir: _includes
